ruby/carManager/config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :carros
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby/carManager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/carManager/app/models/carro.rb
class Carro < ApplicationRecord
	validates :placa, presence: {message: ": Placa deve ser informada"}
	validates :placa, uniqueness: {message: ": Placa já cadastrada"}
	validates :tipo, presence: {message: ": Tipo deve ser informado" }
	validates :ano, presence: {message: ": Ano deve ser informado"}

	def self.get_by_placa(x)
		puts "X: "+x
		self.where(placa: x)
	end
end

ruby/carManager/app/models/cliente.rb
class Cliente < ApplicationRecord
	validates :name, presence: {message: ": Nome deve ser informado"}

	validates :rg, presence: {message: ": RG deve ser informado"}
	validates :rg, uniqueness: {message: ": RG já cadastrado"}

	validates :cpf, presence: {message: ": CPF deve ser informado"}
	validates :cpf, uniqueness: {message: ": CPF já cadastrado"}

	validates :address, presence: {message: ": Endereço deve ser informado" }

	def self.get_by_cpf(c)
		self.where(cpf: c)
	end

end

ruby/carManager/app/models/reserva.rb
class Reserva < ApplicationRecord
	validate :cpf_is_valid
	validate :placa_is_valid
	validate :time_is_valid

	def cpf_is_valid
		cliente = Cliente.get_by_cpf(cpf)
		errors.add(:cpf,"CPF inválido") unless cliente[0]!=nil
	end

	def placa_is_valid
		c = Carro.get_by_placa(carro)
		errors.add(:carro,"Placa inválida") unless c[0]!=nil
	end

	def time_is_valid
		errors.add(:data_inicio, "Data de início é anterior a data atual") unless data_inicio >= Date.today
		errors.add(:data_fim, "Data de início é posterior a data final") unless data_fim >= data_inicio
		reservas = Reserva.where("carro = ? and( 
			(data_inicio <= ? and data_fim >= ?)
			or (data_inicio <= ? and data_fim >= ?)
			or (data_inicio >= ? and data_fim <= ?))",
					carro,data_inicio,data_inicio,data_fim,data_fim,data_inicio,data_fim)

		errors.add(:data_inicio, "Intervalo de tempo não disponível") unless reservas[0]==nil
		errors.add(:data_fim, "Intervalo de tempo não disponível") unless reservas[0]==nil
	end

end

ruby/carManager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ruby/carManager/app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy]

  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1
  # GET /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1
  # PATCH/PUT /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: 'Carro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carro_params
      params.require(:carro).permit(:placa, :tipo, :ano)
    end
end

ruby/carManager/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:name, :address, :cpf, :rg)
    end
end

ruby/carManager/app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:carro, :cliente, :cpf, :data_inicio, :data_fim)
    end
end

ruby/carManager/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/carManager/app/helpers/carros_helper.rb
module CarrosHelper
end

ruby/carManager/app/helpers/clientes_helper.rb
module ClientesHelper
end

ruby/carManager/app/helpers/reservas_helper.rb
module ReservasHelper
end

ruby/carManager/app/views/carros/_form.html.erb
<%= form_with(model: carro, local: true) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :placa %>
    <%= form.text_field :placa, id: :carro_placa %>
  </div>

  <div class="field">
    <%# form.label :tipo %> 
    <!-- <%= form.number_field :tipo, id: :carro_tipo %> -->
    <h4>Tipo do carro:</h4>

    <%= form.radio_button :tipo, 1 , :style => "float:left"%>
    <%= label_tag(:tipo_1, "Urbano")%><br>
    <%= form.radio_button :tipo, 2 , :style => "float:left"%>
    <%= label_tag(:tipo_2, "Motocross")%><br>
    <%= form.radio_button :tipo, 3 , :style => "float:left"%>
    <%= label_tag(:tipo_3, "Luxo")%><br>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :carro_ano , input_html:{ min: '1950', max: '2017' } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ruby/carManager/app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

ruby/carManager/app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Tipo</th>
      <th>Ano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.placa %></td>
        <!-- <td><%= carro.tipo %></td> -->
        <td><%= ["Urbano","Motocross","Luxo"][carro.tipo-1] %></td>
        <td><%= carro.ano %></td>
        <td><%= link_to 'Show', carro %></td>
        <td><%= link_to 'Edit', edit_carro_path(carro) %></td>
        <td><%= link_to 'Destroy', carro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carro', new_carro_path %>

ruby/carManager/app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

ruby/carManager/app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @carro.placa %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @carro.tipo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @carro.ano %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

ruby/carManager/app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cliente_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :cliente_address %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :cliente_cpf %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg, id: :cliente_rg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ruby/carManager/app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

ruby/carManager/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Cpf</th>
      <th>Rg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.name %></td>
        <td><%= cliente.address %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.rg %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

ruby/carManager/app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

ruby/carManager/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cliente.address %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @cliente.rg %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

ruby/carManager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ruby/carManager/app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :carro %>
    <%= form.text_field :carro, id: :reserva_carro %>
  </div>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.text_field :cliente, id: :reserva_cliente %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :reserva_cpf %>
  </div>

  <div class="field">
    <%= form.label :data_inicio %>
    <%= form.datetime_select :data_inicio, id: :reserva_data_inicio %>
  </div>

  <div class="field">
    <%= form.label :data_fim %>
    <%= form.datetime_select :data_fim, id: :reserva_data_fim %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ruby/carManager/app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

ruby/carManager/app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Carro</th>
      <th>Cliente</th>
      <th>Cpf</th>
      <th>Data inicio</th>
      <th>Data fim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.carro %></td>
        <td><%= reserva.cliente %></td>
        <td><%= reserva.cpf %></td>
        <td><%= reserva.data_inicio %></td>
        <td><%= reserva.data_fim %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserva', new_reserva_path %>

ruby/carManager/app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

ruby/carManager/app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Carro:</strong>
  <%= @reserva.carro %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @reserva.cliente %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @reserva.cpf %>
</p>

<p>
  <strong>Data inicio:</strong>
  <%= @reserva.data_inicio %>
</p>

<p>
  <strong>Data fim:</strong>
  <%= @reserva.data_fim %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>